const express = require('express')
const router=express.Router()
const userSchema=require('./User/userController')
router.post('/userregister',userSchema.userreg)
router.post('/userlogin',userSchema.userlogin)
const staffSchema=require('./Staff/staffController')
router.post('/staffregister',staffSchema.staffreg)
const staffmenuSchema = require('./Staff/staffmenuController')
router.post('/staffmenu',staffmenuSchema.upload,staffmenuSchema.staffmenu)
router.post('/menucard',staffmenuSchema.find)
router.post('/starter',staffmenuSchema.Starter)
const contactSchema=require('./User/contactController')
router.post('/contactfeed',contactSchema.contactus)
router.post('/feedback',contactSchema.findall)
const staffmenudeleteschema=require('./Staff/staffmenudeletecontroller')
router.post('/deletecard/:_id',staffmenudeleteschema.deleteById)
module.exports=router