const express = require('express')
const router=express.Router()
const userSchema=require('./User/userController')
router.post('/userregister',userSchema.userreg)
router.post('/userlogin',userSchema.userlogin)
const staffSchema=require('./Staff/staffController')
router.post('/staffregister',staffSchema.staffreg)
const staffmenuSchema = require('./Staff/staffmenuController')
router.post('/staffmenu',staffmenuSchema.upload,staffmenuSchema.staffmenu)
router.post('/menucard',staffmenuSchema.find)
const usercartschema=require('./User/usercartController')
router.post('/usercart',usercartschema.usercart)
router.post("/usercartfind/:_id",usercartschema.finditem)
module.exports=router 