const express = require('express')
const router=express.Router()
const userSchema=require('./User/userController')
router.post('/userregister',userSchema.userreg)
router.post('/userlogin',userSchema.userlogin)
const staffSchema=require('./Staff/staffController')
router.post('/staffregister',staffSchema.upload,staffSchema.staffreg)
router.post('/stafflist',staffSchema.find)
router.post('/stafflogin',staffSchema.stafflogin)
const staffmenuSchema = require('./Staff/staffmenuController')
router.post('/staffmenu',staffmenuSchema.upload,staffmenuSchema.staffmenu)
router.post('/menucard',staffmenuSchema.find)
module.exports=router